import torch
from torch_geometric.data import HeteroData
from torch_geometric.nn import radius_graph
from rdkit import Chem
from rdkit import RDLogger
from scipy.spatial import KDTree
import numpy as np
import os
import re

# Silencia o log do RDKit. Ele emite ~1,2 linha de aviso por complexo
# ("Can't kekulize mol", valências inconsistentes) e o PDBbind tem 19.037 deles:
# são ~23.000 linhas, 2,4 MB, despejadas numa única célula de saída. Num notebook
# isso fica retido no kernel E no .ipynb, e o navegador engasga renderizando tudo.
# Os avisos são esperados — a cascata de tolerância em `_ler_ligante` existe
# justamente para lidar com esses arquivos — e nenhum deles é acionável.
RDLogger.DisableLog('rdApp.*')


def custom_radius_graph(x, r, loop=False):
    """
    Native PyTorch fallback for radius_graph.
    Bypasses the 'torch_cluster' C++ extension dependency which causes AttributeError: 'NoneType' object.
    """
    dist = torch.cdist(x, x)
    mask = dist <= r
    if not loop:
        mask.fill_diagonal_(False)
    return mask.nonzero(as_tuple=False).t().contiguous()

class PharmGraphBuilder:
    def __init__(self, pocket_radius=6.0, interaction_radius=5.0, covalent_radius=2.0):
        self.pocket_radius = pocket_radius
        self.interaction_radius = interaction_radius
        self.covalent_radius = covalent_radius

    def get_atom_features(self, atom):
        """
        Extrai um vetor rico de propriedades químicas de cada átomo.
        Tamanho do Vetor (Input Features) = 13
        """
        hybridization = atom.GetHybridization()
        hyb_encoded = [
            1.0 if hybridization == Chem.rdchem.HybridizationType.SP else 0.0,
            1.0 if hybridization == Chem.rdchem.HybridizationType.SP2 else 0.0,
            1.0 if hybridization == Chem.rdchem.HybridizationType.SP3 else 0.0,
            1.0 if hybridization == Chem.rdchem.HybridizationType.SP3D else 0.0,
            1.0 if hybridization == Chem.rdchem.HybridizationType.SP3D2 else 0.0,
            1.0 if hybridization == Chem.rdchem.HybridizationType.UNSPECIFIED else 0.0,
        ]
        
        # Doador/aceptor de ligação de hidrogênio.
        #
        # Os hidrogênios do PDBbind não são experimentais: o cabeçalho dos arquivos
        # traz "GENERATED BY X-TOOL" e as distâncias N-H medem 1.0400 Å com desvio
        # de 0.0003 Å, ou seja, foram colocados por regra geométrica a partir dos
        # átomos pesados. Como tal, não carregam informação independente e só
        # inflavam o grafo (48,7% dos nós). Mas descartá-los sem mais apagaria a
        # distinção entre uma hidroxila e uma carbonila, que para ligação de
        # hidrogênio é essencial. Estas duas flags são calculadas ENQUANTO os
        # hidrogênios ainda existem e sobrevivem à remoção como propriedade de
        # átomo — a informação é destilada, não perdida.
        doador = 1.0 if atom.HasProp('eh_doador') and atom.GetBoolProp('eh_doador') else 0.0
        z = atom.GetAtomicNum()
        aceptor = 1.0 if (z == 8 or (z == 7 and atom.GetFormalCharge() <= 0)) else 0.0

        return [
            float(atom.GetAtomicNum()),      # Z
            float(atom.GetMass()),           # Massa atômica
            float(atom.GetDegree()),         # Número de ligações
            1.0 if atom.GetIsAromatic() else 0.0, # Aromaticidade
            float(atom.GetIntProp('carga_ph7')       # Estado de ionização em pH ~7
                  if atom.HasProp('carga_ph7')
                  else atom.GetFormalCharge()),
            doador,                          # Doador de ligação de H
            aceptor                          # Aceptor de ligação de H
        ] + hyb_encoded

    @staticmethod
    def _ler_pdb_sanitizado(caminho, eh_proteina=True):
        """Lê um PDB preservando aromaticidade, hibridização e removendo hidrogênios.

        O caminho ingênuo — `MolFromPDBFile(removeHs=True, sanitize=False)` — falha
        silenciosamente em três frentes, porque as três dependem da sanitização:

          * aromaticidade nunca é percebida (anéis de Phe, Tyr, Trp e His entram
            como alifáticos);
          * hibridização fica UNSPECIFIED em todos os átomos;
          * `removeHs` não tem efeito.

        Medido no dataset: com o parse antigo, 7 das 11 features dos átomos de
        proteína eram constantes, e 48,5% dos átomos eram hidrogênios que deveriam
        ter sido descartados.

        Sanitizar por completo, porém, quebra em boa parte dos PDB experimentais,
        que trazem valências inconsistentes, resíduos incompletos e metais. A
        solução é sanitizar tudo EXCETO `SANITIZE_PROPERTIES`, que é justamente a
        checagem de valência. Verificado em 400 proteínas do PDBbind: zero falhas,
        mesma taxa do parse anterior, com aromaticidade e hibridização recuperadas
        em 100% dos casos.
        """
        mol = Chem.MolFromPDBFile(caminho, removeHs=False, sanitize=False)
        if mol is None:
            return None

        ops = Chem.SanitizeFlags.SANITIZE_ALL ^ Chem.SanitizeFlags.SANITIZE_PROPERTIES
        if Chem.SanitizeMol(mol, sanitizeOps=ops, catchErrors=True) != Chem.SanitizeFlags.SANITIZE_NONE:
            return None

        PharmGraphBuilder._marcar_doadores(mol)
        PharmGraphBuilder._marcar_cargas(mol, eh_proteina)

        try:
            mol = Chem.RemoveHs(mol, sanitize=False)
        except Exception:
            pass  # sem hidrogênios explícitos, ou remoção não aplicável
        return mol

    @classmethod
    def _ler_ligante(cls, caminho):
        """Lê o ligante por cascata de tolerância crescente.

        Uma fração dos ligantes do PDBbind não passa na sanitização completa do
        RDKit — tipicamente por valência ou aromaticidade inconsistente no `.sdf`.
        Com uma única tentativa, esses complexos eram simplesmente descartados:
        **41 dos 285 do CASF core set**, ou 14% do conjunto de teste, além de
        centenas de amostras de treino. Como o benchmark publicado usa os 285,
        faltar 14% também quebrava a comparabilidade com a literatura.

        A cascata tenta, em ordem:
          1. `.sdf` com sanitização completa — melhor caso, química toda percebida;
          2. `.sdf` com sanitização tolerante (sem a checagem de valência);
          3. `.mol2` correspondente, também tolerante.

        Medido nos 8 casos inspecionados: nenhum passa em (1) ou (2), e todos
        passam em (3). O `.mol2` acompanha cada complexo do PDBbind, então o
        fallback não exige baixar nada.
        """
        ops = Chem.SanitizeFlags.SANITIZE_ALL ^ Chem.SanitizeFlags.SANITIZE_PROPERTIES

        def finalizar(mol):
            if mol is None:
                return None
            cls._marcar_doadores(mol)
            cls._marcar_cargas(mol, eh_proteina=False)
            try:
                return Chem.RemoveHs(mol, sanitize=False)
            except Exception:
                return mol

        mol = Chem.MolFromMolFile(caminho, removeHs=False, sanitize=True)
        if mol is not None:
            return finalizar(mol)

        mol = Chem.MolFromMolFile(caminho, removeHs=False, sanitize=False)
        if mol is not None and Chem.SanitizeMol(mol, sanitizeOps=ops, catchErrors=True) == Chem.SanitizeFlags.SANITIZE_NONE:
            return finalizar(mol)

        caminho_mol2 = re.sub(r'\.sdf$', '.mol2', caminho)
        if caminho_mol2 != caminho and os.path.exists(caminho_mol2):
            mol = Chem.MolFromMol2File(caminho_mol2, removeHs=False, sanitize=False)
            if mol is not None and Chem.SanitizeMol(mol, sanitizeOps=ops, catchErrors=True) == Chem.SanitizeFlags.SANITIZE_NONE:
                return finalizar(mol)

        return None

    @staticmethod
    def _marcar_doadores(mol):
        """Marca N/O que carregam hidrogênio, ANTES de os hidrogênios sumirem.

        Não dá para usar `GetTotalNumHs()` depois: ele depende de
        `SANITIZE_PROPERTIES`, que é justamente a etapa que pulamos por quebrar em
        PDB experimental. Medido em 10gs: 227 doadores por `GetTotalNumHs()` contra
        576 contando vizinhos explícitos — o valor correto é o segundo.
        """
        for atom in mol.GetAtoms():
            eh = (atom.GetAtomicNum() in (7, 8) and
                  any(v.GetAtomicNum() == 1 for v in atom.GetNeighbors()))
            atom.SetBoolProp('eh_doador', bool(eh))

    # Grupos ionizáveis do ligante em pH ~7, por SMARTS. Casam a forma NEUTRA
    # também (`OX2H1`, `NX3;H2,H1`) de propósito: PDB e SDF do PDBbind não trazem
    # estado de protonação, então carboxilato chega como COOH e amina como NH2.
    _SMARTS_ANIONICO = [
        "[CX3](=O)[OX1H0-,OX2H1]",              # carboxilato / ácido carboxílico
        "[PX4](=O)([OX1H0-,OX2H1])[OX1H0-,OX2H1]",  # fosfato / fosfonato
        "[SX4](=O)(=O)[OX1H0-,OX2H1]",          # sulfonato
        "c1nnn[nH0-,nH1]1",                      # tetrazol
    ]
    _SMARTS_CATIONICO = [
        "[NX3;H2,H1,H0;!$(N[!#6]);!$(N=*);!$(N#*);!$(Nc)]",  # amina alifática
        "[NX3][CX3](=[NX2])[NX3]",               # guanidínio
        "[NX3][CX3]=[NX2]",                      # amidina
        "[NX4+]",                                # amônio quaternário
    ]

    # Lado da proteína: resíduo + nome do átomo. Mais confiável que SMARTS, porque
    # a topologia dos aminoácidos é conhecida e o PDB traz os nomes canônicos.
    # His fica de fora de propósito: pKa ≈ 6, o estado é genuinamente ambíguo e
    # incluí-la marcaria como catiônico algo que na metade dos casos não é.
    _ANIONICO_PROT = {("ASP", "OD1"), ("ASP", "OD2"),
                      ("GLU", "OE1"), ("GLU", "OE2")}
    _CATIONICO_PROT = {("ARG", "NE"), ("ARG", "NH1"), ("ARG", "NH2"),
                       ("LYS", "NZ")}

    _CACHE_PADROES = None

    @classmethod
    def _padroes_compilados(cls):
        """SMARTS compilados UMA vez, não a cada molécula.

        Medido em 2/set/2026: compilar os oito padrões dentro do laço dobrava o
        custo por complexo (1,4–2,0× em cinco casos medidos). Num job de 19 mil
        complexos isso é a diferença entre 4 h e 8 h. `MolFromSmarts` de padrões
        recursivos como `[NX3;...;!$(N[!#6])]` não é barato, e o resultado é
        constante — não havia razão para repetir.
        """
        if cls._CACHE_PADROES is None:
            pares = ([(sm, -1) for sm in cls._SMARTS_ANIONICO] +
                     [(sm, 1) for sm in cls._SMARTS_CATIONICO])
            cls._CACHE_PADROES = [(Chem.MolFromSmarts(sm), v)
                                  for sm, v in pares if Chem.MolFromSmarts(sm) is not None]
        return cls._CACHE_PADROES

    @classmethod
    def _marcar_cargas(cls, mol, eh_proteina):
        """Atribui estado de ionização em pH ~7, que a leitura não percebe.

        Medido antes desta correção: **1,1% dos átomos da proteína e 1,9% do
        ligante** tinham carga formal diferente de zero. Numa proteína real,
        Asp/Glu somam ~10% dos resíduos e Arg/Lys ~11%, todos carregados em pH
        fisiológico. Ou seja, a coluna de carga era praticamente uma constante —
        um canal de entrada morto para o modelo, e um tipo farmacofórico
        (iônico) que nunca seria rotulado.

        A carga é gravada em `carga_ph7` e não em `SetFormalCharge`, para não
        interferir na valência que o RDKit usa em outras etapas.
        """
        for a in mol.GetAtoms():
            a.SetIntProp('carga_ph7', 0)

        if eh_proteina:
            for a in mol.GetAtoms():
                info = a.GetPDBResidueInfo()
                if info is None:
                    continue
                chave = (info.GetResidueName().strip().upper(),
                         info.GetName().strip().upper())
                if chave in cls._ANIONICO_PROT:
                    a.SetIntProp('carga_ph7', -1)
                elif chave in cls._CATIONICO_PROT:
                    a.SetIntProp('carga_ph7', 1)
            return

        for padrao, valor in cls._padroes_compilados():
            try:
                casos = mol.GetSubstructMatches(padrao, maxMatches=200)
            except Exception:
                continue
            for grupo in casos:
                for idx in grupo:
                    a = mol.GetAtomWithIdx(idx)
                    # Só o átomo que de fato carrega a carga: O/N do grupo.
                    if a.GetAtomicNum() in (7, 8) and a.GetIntProp('carga_ph7') == 0:
                        a.SetIntProp('carga_ph7', valor)

    def parse_ligand(self, ligand_path):
        if ligand_path.endswith('.pdb'):
            mol = self._ler_pdb_sanitizado(ligand_path, eh_proteina=False)
        else:
            mol = self._ler_ligante(ligand_path)

        if mol is None: raise ValueError("Falha ao ler ligante")

        conf = mol.GetConformer()
        positions = conf.GetPositions()
        features = [self.get_atom_features(atom) for atom in mol.GetAtoms()]

        return np.array(positions), np.array(features)

    def parse_protein(self, protein_path):
        mol = self._ler_pdb_sanitizado(protein_path)
        if mol is None: raise ValueError("Falha ao ler proteina")

        conf = mol.GetConformer()
        positions = conf.GetPositions()
        features = [self.get_atom_features(atom) for atom in mol.GetAtoms()]

        return np.array(positions), np.array(features)

    def selecionar_bolso(self, lig_pos, prot_pos):
        """Índices dos átomos de proteína a até `pocket_radius` do ligante.

        Extraído de `build_hetero_graph` para que a análise de consenso use
        exatamente a mesma seleção — duplicar essa lógica seria a forma óbvia de
        os dois divergirem em silêncio.
        """
        tree = KDTree(prot_pos)
        vizinhos = tree.query_ball_point(lig_pos, r=self.pocket_radius)
        return np.unique([i for sub in vizinhos for i in sub]).astype(int)

    def residuos_proteina(self, protein_path):
        """Chave (num_residuo, nome_residuo) para cada átomo, na ordem de parse_protein.

        A chave omite a cadeia de propósito: dentro de um cluster do CASF os cinco
        complexos são do mesmo alvo, mas nem sempre com a mesma letra de cadeia
        (num cluster inspecionado, quatro usam 'A' e um usa 'B'). Número e nome do
        resíduo são estáveis entre as entradas.
        """
        mol = self._ler_pdb_sanitizado(protein_path)
        if mol is None:
            raise ValueError("Falha ao ler proteina")
        chaves = []
        for atom in mol.GetAtoms():
            info = atom.GetPDBResidueInfo()
            if info is None:
                chaves.append((-1, '???'))
            else:
                chaves.append((info.GetResidueNumber(), info.GetResidueName().strip()))
        return chaves

    def build_hetero_graph(self, protein_path, ligand_path):
        lig_pos, lig_feat = self.parse_ligand(ligand_path)
        prot_pos, prot_feat = self.parse_protein(protein_path)

        # Filtrar o bolso (Pocket) usando KDTree
        pocket_indices = self.selecionar_bolso(lig_pos, prot_pos)

        if len(pocket_indices) == 0:
            raise ValueError(
                "Nenhum átomo da proteína foi encontrado próximo ao ligante! "
                "Isso significa que as coordenadas do ligante (.sdf) estão fora do bolso do receptor. "
                "Você precisa realizar o Docking Molecular (Ex: AutoDock Vina) ou Alinhamento 3D "
                "para posicionar o fármaco dentro da proteína antes de prever a afinidade."
            )
            
        pocket_pos = prot_pos[pocket_indices]
        pocket_feat = prot_feat[pocket_indices]

        data = HeteroData()

        # ==============================================================
        # 1. NÓS (Atribuindo a química quântica)
        # ==============================================================
        data['ligand'].x = torch.tensor(lig_feat, dtype=torch.float)
        data['ligand'].pos = torch.tensor(lig_pos, dtype=torch.float)

        data['protein'].x = torch.tensor(pocket_feat, dtype=torch.float)
        data['protein'].pos = torch.tensor(pocket_pos, dtype=torch.float)

        # ==============================================================
        # 2. ARESTAS INTRAMOLECULARES (O "Esqueleto" das moléculas)
        # ==============================================================
        # Conecta átomos do ligante entre si (Ligações covalentes)
        lig_edge_idx = custom_radius_graph(data['ligand'].pos, r=self.covalent_radius, loop=False)
        lig_edge_attr = torch.norm(data['ligand'].pos[lig_edge_idx[0]] - data['ligand'].pos[lig_edge_idx[1]], dim=1).view(-1, 1)
        data['ligand', 'covalent', 'ligand'].edge_index = lig_edge_idx
        data['ligand', 'covalent', 'ligand'].edge_attr = lig_edge_attr

        # Conecta átomos da proteína entre si (Backbone e cadeias laterais)
        prot_edge_idx = custom_radius_graph(data['protein'].pos, r=self.covalent_radius, loop=False)
        prot_edge_attr = torch.norm(data['protein'].pos[prot_edge_idx[0]] - data['protein'].pos[prot_edge_idx[1]], dim=1).view(-1, 1)
        data['protein', 'covalent', 'protein'].edge_index = prot_edge_idx
        data['protein', 'covalent', 'protein'].edge_attr = prot_edge_attr

        # ==============================================================
        # 3. ARESTAS INTERMOLECULARES (A Interação Droga-Alvo)
        # ==============================================================
        tree_pocket = KDTree(pocket_pos)
        interaction_pairs = tree_pocket.query_ball_point(lig_pos, r=self.interaction_radius)

        lig_edges = []
        prot_edges = []
        edge_dist = []

        for lig_idx, prot_neighbors in enumerate(interaction_pairs):
            for prot_idx in prot_neighbors:
                lig_edges.append(lig_idx)
                prot_edges.append(prot_idx)
                dist = np.linalg.norm(lig_pos[lig_idx] - pocket_pos[prot_idx])
                edge_dist.append(dist)

        inter_edge_index = torch.tensor([lig_edges, prot_edges], dtype=torch.long)
        inter_edge_attr = torch.tensor(edge_dist, dtype=torch.float).view(-1, 1)

        # Aresta Ligante -> Proteína
        data['ligand', 'interacts', 'protein'].edge_index = inter_edge_index
        data['ligand', 'interacts', 'protein'].edge_attr = inter_edge_attr
        
        # Aresta Proteína -> Ligante (Fundamental para a troca de mensagens bidirecional)
        rev_inter_edge_index = torch.tensor([prot_edges, lig_edges], dtype=torch.long)
        data['protein', 'interacts', 'ligand'].edge_index = rev_inter_edge_index
        data['protein', 'interacts', 'ligand'].edge_attr = inter_edge_attr

        return data
